alias daily='cd ~/Documents/notes/daily_tasks/';
alias notes='cd ~/Documents/notes/';
alias apr='cd ~/Documents/HR/APR/';
alias aquilon='~/dotfiles/tmux/aquilon_session.sh';
alias please='sudo !!'
alias python='python3';
alias workon='source .venv/bin/activate';
alias workoff='deactivate';
alias wincode='cd ~/Documents/code/';
alias slm_notes='cd ~/Documents/notes/daily_tasks/ && grep -r -i slm .';
alias beta='cd ~/beta-infrastructure-portal/infrastructure-portal'
alias ..='cd ../';
alias ...='cd ../../';
alias ....='cd ../../../';
alias gh_token='cat ~/git_tokens/gh_token';
