alias daily='cd ~/Documents/notes/daily_tasks/';
alias notes='cd ~/Documents/notes/';
alias apr='cd ~/Documents/HR/APR/';
alias aquilon='~/dotfiles/tmux/aquilon_session.sh';
alias please='sudo !!'
alias python='python3';
alias workon='source .venv/bin/activate';
alias workoff='deactivate';
alias wincode='cd ~/Documents/code/';
alias slm_notes='cd ~/Documents/notes/daily_tasks/ && grep -r -i slm .';
alias ..='cd ../';
alias ...='cd ../../';
alias ....='cd ../../../';
alias gh_token='cat ~/tokens/gh_token';
alias nr_token='cat ~/tokens/nr_token';
alias teams_reset='rm -rf /mnt/c/Users/adg51575/AppData/Roaming/Microsoft/Teams/*'
alias docker-full-restart='docker compose down; docker compose rm -fv; docker compose up -d'
alias rails='cd ~/rails/raildataingestion-docs'
alias fuck='sudo $(history -p !!)'
alias common='cd ~/.steam/steam/steamapps/common/'
alias ksp-server='dotnet ~/ksp_mods/LMPServer/Server.dll'
alias ksp-cd="cd .steam/debian-installation/steamapps/common/Kerbal\ Space\ Program/"
