alias ....='cd ../../../';
alias ...='cd ../../';
alias ..='cd ../';
alias accounts='cd /home/josh/infrastructure-portal/modules/custom/rii_accounts';
alias apr='cd ~/Documents/HR/APR/';
alias aquilon='~/dotfiles/tmux/aquilon_session.sh';
alias beta='cd ~/beta-infrastructure-portal/infrastructure-portal'
alias daily='cd ~/Documents/notes/daily_tasks/';
alias notes='cd ~/Documents/notes/';
alias please='sudo !!'
alias python='python3';
alias slm_notes='cd ~/Documents/notes/daily_tasks/ && grep -r -i slm .';
alias wincode='cd ~/Documents/code/';
alias workoff='deactivate';
alias workon='source .venv/bin/activate';
alias gh_token='cat ~/Documents/notes/gh_token.txt';
alias myip='dig TXT +short o-o.myaddr.l.google.com @ns1.google.com';
